---
title: "Merge-table"
date: "2022-08-26"
---
Merge alpha-diversity table
1-library
```{r}
library(readr)
```
2-Import alpha-diversity.tsv file
```{r}
shannon <- read_tsv("shannon/alpha-diversity.tsv")
colnames(shannon)[colnames(shannon) == "...1"] <- "sample-id"
chao1 <- read_tsv("chao1/alpha-diversity.tsv")
colnames(chao1)[colnames(chao1) == "...1"] <- "sample-id"
simpson <- read_tsv("simpson/alpha-diversity.tsv")
colnames(simpson)[colnames(simpson) == "...1"] <- "sample-id"
faithpd <- read_tsv("faithpd/alpha-diversity.tsv")
colnames(faithpd)[colnames(faithpd) == "...1"] <- "sample-id"
pielou <- read_tsv("pielou/alpha-diversity.tsv")
colnames(pielou)[colnames(pielou) == "...1"] <- "sample-id"
ace <- read_tsv("ace/alpha-diversity.tsv")
colnames(ace)[colnames(ace) == "...1"] <- "sample-id"
```
3-Merge table
```{r}
alphadiversity <- merge(shannon, faithpd, by = "sample-id", all =  TRUE)
alphadiversity <- merge(alphadiversity, chao1, by = "sample-id", all =  TRUE)
alphadiversity <- merge(alphadiversity, ace, by = "sample-id", all =  TRUE)
alphadiversity <- merge(alphadiversity, simpson, by = "sample-id", all =  TRUE)
alphadiversity <- merge(alphadiversity, pielou, by = "sample-id", all =  TRUE)
```

ABOUT MERGE COMMAND:
Inner join: Merge what are same in 2 table
```{r}
inner <- merge(table1, table2, by = column)
```
Left (outer) join: Keep table 1 + what are in table 2 same in table 1
```{r}
left  <- merge(flights, weather, by = mergeCols, all.x = TRUE)
```
Right (outer) join: Keep table 2 + what are in table 1 same in table 2
```{r}
right <- merge(flights, weather, by = mergeCols, all.y = TRUE)
```
Full (outer) join: join all
```{r}
full <- merge(flights, weather, by = mergeCols, all = TRUE)
```

